# Generated by Django 2.2.24 on 2021-08-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleModel',
            new_name='ArticleModel1',
        ),
    ]
